install:
 - source ./texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
  - wget https://raw.githubusercontent.com/texjporg/ptex-manual/master/ptex-manual.tex
  - platex -kanji=utf8 ptex-manual.tex
  - makeindex -s gind.ist -o ptex-manual.ind ptex-manual.idx
  - platex ptex-manual.tex
  - dvipdfmx -f ptex-ipaex.map -f uptex-ipaex.map -f otf-ipaex.map ptex-manual
# - texlua build.lua check -q -H

#notifications:
#  email:
#    recipients:
#      - issue@texjp.org
#    on_success: change
#    on_failure: always
#    on_start:   never

