install:
 - source ./texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
# texjporg/ptex-manual
  - git clone https://github.com/texjporg/ptex-manual
  - cd ptex-manual
  - platex -kanji=utf8 ptex-manual.tex
  - makeindex -s gind.ist -o ptex-manual.ind ptex-manual.idx
  - platex ptex-manual.tex
  - dvipdfmx -f ptex-ipaex.map -f uptex-ipaex.map -f otf-ipaex.map ptex-manual.dvi
  - cd ..
# texjporg/mendex-doc
  - git clone https://github.com/texjporg/mendex-doc
  - cd mendex-doc
  - platex -kanji=utf8 mendex.tex
  - platex -kanji=utf8 mendex.tex
  - dvipdfmx -f ptex-ipaex.map -f uptex-ipaex.map -f otf-ipaex.map mendex.dvi
  - cd ..
# texjporg/ptex-base/tests
  - git clone https://github.com/texjporg/ptex-base
  - cd ptex-base/tests
  - ptex -kanji=utf8 sample.tex
  - dvipdfmx -f ptex-ipaex.map -f uptex-ipaex.map -f otf-ipaex.map sample.dvi
  - eptex -kanji=utf8 sample.tex
  - dvipdfmx -f ptex-ipaex.map -f uptex-ipaex.map -f otf-ipaex.map sample.dvi
  - cd ..
# texjporg/platex/tests
  - git clone https://github.com/texjporg/platex
  - cd platex/tests
  - cp ../../makefile.wildcard Makefile
  - make test
  - cd ../..
# original from latex3
# - texlua build.lua check -q -H

#notifications:
#  email:
#    recipients:
#      - issue@texjp.org
#    on_success: change
#    on_failure: always
#    on_start:   never

